#baseurl: "/2017"

title: "BuildingBloCS"
tagline: "High School Computer Science Conference"
date: "7 June"
location: "NUS School of Computing"

exclude:
  - README.md
  - assets/sass
  - package.json
  - package-lock.json
  - node_modules/
  - Gruntfile.js
